### ISSUE TITLE
Error: Can't use "mapLoadableActions" without Vuex.

### ISSUE THREAD

**Issue by DanHulton** [VitorLuizC/vue-loadable#7]
In main.js:
```
import Vue from 'vue';
import Vuex from 'vuex';
import Loadable from 'vue-loadable';
import store from './store';

Vue.use(Vuex);
Vue.use(Loadable);

new Vue({
  store,
  render: h => h(App),
}).$mount('#app');
```
In RefiningDialog.vue:
```
import { mapLoadableActions } from 'vue-loadable';

export default {
  methods: {
    ...mapLoadableActions('Refining', [
      'newRefiningTask',
    ]),
  },
};
```
However, on loading page, I get: `Error: Can't use "mapLoadableActions" without Vuex.`.

I dug into `vue-loadable.mjs`, and adding `import Vuex from 'vuex';` to the top, just under the `import Vue` line, makes it all work as expected (and it works a treat, really handy solution!), but mucking about in the `dist` folder in `node_modules` can't be the intended solution.  =)

I feel like I'm missing something in how I'm setting this all up, but even comparing it to examples in the repo, it appears to be correct.  There aren't any tests against `mapLoadableActions`, so I'm kind of at a loss from where to look next.

Ideally I'm just overlooking something, but even still, I'd be interested in submitting a PR with some extra documentation to help out folks who run into troubles like myself.

**Comment by VitorLuizC** [comment]
Probably related to this nasty strategy to support projects without Vuex.

https://github.com/VitorLuizC/vue-loadable/blob/46ce3f6771c2df5e957b1e4e6752a8ecedd47a6c/src/mapActions.ts#L10-L21

I'll fix this ASAP.

**Comment by VitorLuizC** [comment]
The example provided on this repository and a CodeSandbox I've made right now seems working fine.

https://codesandbox.io/s/vue-template-qohr2

Probably because CodeSandbox, Poi and Webpack interops CommonJS and ESM modules.

**Comment by VitorLuizC** [comment]
Sorry to took so long, I finally find a way to support any environment and also provide a `mapLoadableActions` function. This night I'll fix this and publish a new version.

**Comment by DanHulton** [comment]
No worries!  I actually really appreciate you taking the time to look into it at all.  For now, I've just been using `patch-package` to manually import Vuex, so I haven't been held back in the meantime, but it'll be nice to go back to using the package at an official version without any modifications!

**Comment by VitorLuizC** [comment]
Finally fixed this. I've used `mapLoadableMethods` like strategy pattern with `Vuex.mapActions` and it worked just fine!

```vue
<script>
import { mapActions } from 'vuex';
import { mapLoadableMethods } from 'vue-loadable';

export default {
  methods: mapLoadableMethods(
    mapActions([
      'signInUser',
      'signUpUser'
    ])
  )
};
```
